package main

// CV is the structure of the cv.json file generated by `applyme init`.
type CV struct {
	Personal   Personal     `json:"personal"`
	Summary    []string     `json:"summary,omitempty"`
	Private    []string     `json:"private,omitempty"`
	Experience []Experience `json:"experience,omitempty"`
	Education  []Education  `json:"education,omitempty"`
	Skills     []SkillGroup `json:"skills,omitempty"`
}

// Personal holds identity, contact and address details.
type Personal struct {
	Title          string  `json:"title,omitempty"`
	FirstName      string  `json:"first_name"`
	LastName       string  `json:"last_name"`
	BirthName      string  `json:"birth_name,omitempty"`
	NameChangeDate string  `json:"name_change_date,omitempty"`
	DateOfBirth    string  `json:"date_of_birth,omitempty"`
	PlaceOfBirth   string  `json:"place_of_birth,omitempty"`
	Address        Address `json:"address"`
	Phone          string  `json:"phone"`
	Email          string  `json:"email"`
	Nationality    string  `json:"nationality,omitempty"`
}

type Address struct {
	Street  string `json:"street"`
	Zip     string `json:"zip"`
	City    string `json:"city"`
	Country string `json:"country"`
}

// Experience is one position in the work history, optionally broken down
// into individual Projects.
type Experience struct {
	Company       string `json:"company"`
	ParentCompany string `json:"parent_company,omitempty"`
	URL           string `json:"url,omitempty"`
	Location      string `json:"location,omitempty"`
	Title         string `json:"title"`

	EmploymentType string `json:"employment_type,omitempty"`
	// WorkloadPercent is freeform to allow both a single value ("80") and a
	// range ("80-100").
	WorkloadPercent string `json:"workload_percent,omitempty"`
	WorkloadNote    string `json:"workload_note,omitempty"`

	Start string `json:"start"`
	End   string `json:"end,omitempty"`

	Description      string    `json:"description,omitempty"`
	Responsibilities []string  `json:"responsibilities,omitempty"`
	Subjects         []string  `json:"subjects,omitempty"`
	Stack            []string  `json:"stack,omitempty"`
	Projects         []Project `json:"projects,omitempty"`

	// Hidden excludes the entry from generated CVs by default, e.g. minor
	// side jobs kept in the data for reference only.
	Hidden bool `json:"hidden,omitempty"`
}

// Project is a specific engagement within an Experience entry.
type Project struct {
	Name        string `json:"name"`
	Client      string `json:"client,omitempty"`
	URL         string `json:"url,omitempty"`
	Description string `json:"description,omitempty"`
	// Importance ranks projects within an Experience entry (higher = more
	// relevant to lead with), 0 if not ranked.
	Importance int      `json:"importance,omitempty"`
	Roles      []string `json:"roles,omitempty"`
	Stack      []string `json:"stack,omitempty"`
}

type Education struct {
	Institution     string `json:"institution"`
	Degree          string `json:"degree"`
	Focus           string `json:"focus,omitempty"`
	Start           string `json:"start,omitempty"`
	End             string `json:"end,omitempty"`
	Graduated       bool   `json:"graduated,omitempty"`
	GraduationDate  string `json:"graduation_date,omitempty"`
	CertificateDate string `json:"certificate_date,omitempty"`
}

// SkillGroup buckets related Skills under a shared category.
type SkillGroup struct {
	Category string  `json:"category"`
	Items    []Skill `json:"items"`
}

// Skill level is on a scale of 1 (basic) to 3 (expert).
type Skill struct {
	Name  string `json:"name"`
	Level int    `json:"level"`
	Note  string `json:"note,omitempty"`
}
