package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CV is the structure of the cv.json file generated by `applyme init`.
type CV struct {
	Name       string   `json:"name"`
	Email      string   `json:"email"`
	Phone      string   `json:"phone"`
	Summary    string   `json:"summary"`
	Experience []string `json:"experience"`
	Education  []string `json:"education"`
	Skills     []string `json:"skills"`
}

var cvTemplate = CV{
	Experience: []string{},
	Education:  []string{},
	Skills:     []string{},
}

const envTemplate = `# applyme settings and api keys
`

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	force := fs.Bool("force", false, "overwrite existing files with default ones")
	if err := fs.Parse(args); err != nil {
		return err
	}

	entries, err := os.ReadDir(".")
	if err != nil {
		return fmt.Errorf("reading current directory: %w", err)
	}

	if len(entries) > 0 {
		fmt.Printf("warning: current folder is not empty (%d existing entries)\n", len(entries))
		if !confirm("continue anyway?") {
			fmt.Println("aborted")
			return nil
		}
	}

	cvJSON, err := marshalJSONIndent(cvTemplate)
	if err != nil {
		return fmt.Errorf("marshaling cv template: %w", err)
	}

	files := []struct {
		name    string
		content []byte
		mode    os.FileMode
	}{
		{"cv.json", cvJSON, 0644},
		{".env", []byte(envTemplate), 0600},
	}

	for _, f := range files {
		path := filepath.Join(".", f.name)
		if !*force {
			if _, err := os.Stat(path); err == nil {
				fmt.Printf("skipping %s (already exists)\n", f.name)
				continue
			}
		}
		if err := os.WriteFile(path, f.content, f.mode); err != nil {
			return fmt.Errorf("writing %s: %w", f.name, err)
		}
		fmt.Printf("created %s\n", f.name)
	}

	fmt.Println("project initialized")
	return nil
}

func confirm(prompt string) bool {
	fmt.Printf("%s [y/N] ", prompt)
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	return line == "y" || line == "yes"
}
